### ISSUE TITLE
 install the custom differentiable forward projection operator

### ISSUE THREAD

**Issue by Floyd809** [cpeng93/XraySyn#1]
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy) 

This error occurred in colab when i run
ct2xray_real.py
cloud you help me？Thank you very much!

**Comment by cpeng93** [comment]
Hi @Floyd809 I made some updates, please see if you still have problems

**Comment by Floyd809** [comment]
> Hi @Floyd809 I made some updates, please see if you still have problems

Thank you for your reply! The Compile Errors about  projection operator have solved,but when I run command:
'python script/test_ct2xray_real.py ct2xray_real_gan_meta', Googel Colab reported the following errors:


================= Options =================
data:
  batch_size: 8
  data_dir: data/lidc/ct
  param_bound:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  same_proj: true
model:
  beta1: 0.5
  detector_shape:
  - 128
  - 128
  interp: nearest
  learn:
    proj1_w: 0.0
    proj2_w: 1.0
    proj_adv: 0.0
    proj_t: l1
    vol_t: l1
    vol_w: 0.0
  lr: 0.0001
  num_feats_2d: 32
  num_feats_3d: 16
  num_layers_2d: 5
  num_layers_3d: 5
  pixel_size:
  - 1.0
  - 1.0
  volume_shape:
  - 128
  - 128
  - 128
schedule:
  num_epoch: 100
  print_freq: 5
  save_freq: 1
  visual_freq: 10
===========================================
============ Model Initialized ============
DataParallel(
  (module): UnetGenerator(
    (down0): UnetDown(
      (conv): Conv3d(1, 96, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      (leaky_relu): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (down1): UnetDown(
      (conv): Conv3d(96, 192, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      (norm): BatchNorm3d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_relu): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (down2): UnetDown(
      (conv): Conv3d(192, 384, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      (norm): BatchNorm3d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_relu): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (down3): UnetDown(
      (conv): Conv3d(384, 768, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      (norm): BatchNorm3d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_relu): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (down4): UnetDown(
      (conv): Conv3d(768, 768, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      (norm): BatchNorm3d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_relu): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (down5): UnetDown(
      (conv): Conv3d(768, 768, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      (norm): BatchNorm3d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_relu): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (up5): UnetUp(
      (deconv): Sequential(
        (0): Upsample(scale_factor=2.0, mode=trilinear)
        (1): Conv3d(768, 768, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
      )
      (norm): BatchNorm3d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (up4): UnetUp(
      (deconv): Sequential(
        (0): Upsample(scale_factor=2.0, mode=trilinear)
        (1): Conv3d(1536, 768, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
      )
      (norm): BatchNorm3d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (up3): UnetUp(
      (deconv): Sequential(
        (0): Upsample(scale_factor=2.0, mode=trilinear)
        (1): Conv3d(1536, 384, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
      )
      (norm): BatchNorm3d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (up2): UnetUp(
      (deconv): Sequential(
        (0): Upsample(scale_factor=2.0, mode=trilinear)
        (1): Conv3d(768, 192, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
      )
      (norm): BatchNorm3d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (up1): UnetUp(
      (deconv): Sequential(
        (0): Upsample(scale_factor=2.0, mode=trilinear)
        (1): Conv3d(384, 96, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
      )
      (norm): BatchNorm3d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (up0): UnetUp(
      (deconv): Sequential(
        (0): Upsample(scale_factor=2.0, mode=trilinear)
        (1): Conv3d(192, 3, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
      )
      (tanh): Tanh()
    )
  )
)
===========================================
Number of parameters: 0.0000e+00

============ Model Initialized ============
...
===========================================
Number of parameters: 1.2279e+08

[]
test_data/h1301.png
Traceback (most recent call last):
  File "script/test_ct2xray_real.py", line 34, in <module>
    xray_pred, xray_refine, mat_pred, mat_refine, _,_ = model.test(data['data'])
  File "./xraysyn/models/ct2xray_real_gan_meta.py", line 126, in test
    vol_pred_temp = self.net3d(vol_in)*0.5+0.5
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./xraysyn/networks/unet.py", line 56, in forward
    x0, x1 = down(x1_down[-1])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./xraysyn/networks/unet.py", line 234, in forward
    else: x0 = self.conv(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1109, in _call_impl
    result = hook(self, input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/spectral_norm.py", line 105, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/spectral_norm.py", line 84, in compute_weight
    v = normalize(torch.mv(weight_mat.t(), u), dim=0, eps=self.eps, out=v)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`

I have tried to reduce the batch_size,but it doesn't work.
Ｃloud you help me？Thank you very much!

**Comment by cpeng93** [comment]
1. Did you download the checkpoint and put it into the proper folder? 
2. The CUDA error seems to be a CUDA version issue. Did you install an environment as listed in the repo?

**Comment by Floyd809** [comment]
> 1. Did you download the checkpoint and put it into the proper folder?
> 2. The CUDA error seems to be a CUDA version issue. Did you install an environment as listed in the repo?




Thank you for your reply, I have solved the reported error, which is indeed an environment configuration problem. Is there any requirement for the format of the input test image? How to test with other real x-ray or ct？

**Comment by cpeng93** [comment]
I am not sure what you mean by testing on CTs, but currently you should crop real x-rays such that they look similarly to the provided examples for the pre-trained model to work.
